### ISSUE TITLE
Replace godep with dep, and ignore vendor file

### ISSUE THREAD

**Issue by smartinov** [mongo-go/lock#5]
Since godep is deprecated as specified in the repository https://github.com/tools/godep, dep should be used instead, and vendor folder ignored since the vendor folder is dependency related.

Relevant links:
https://www.reddit.com/r/golang/comments/6b9817/should_i_add_vendor_directory_into_gitignore_if_i/
https://golang.github.io/dep/docs/FAQ.html#should-i-commit-my-vendor-directory

**Comment by michaelfinch** [comment]
Thanks for filing this, I've been meaning to make the switch

**Comment by michaelfinch** [comment]
I've switched to dep, and added the vendor dir to .gitignore here: https://github.com/square/mongo-lock/pull/1
